root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./starter/main.go"
  bin = "./tmp/main.exe"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "yaml", "html", "css"]

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
