package cb

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/joho/godotenv"
)

// AIChatMessage represents a role/content message pair in OpenAI API
type AIChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// AIChatRequest represents the OpenAI chat completion payload
type AIChatRequest struct {
	Model       string          `json:"model"`
	Messages    []AIChatMessage `json:"messages"`
	Temperature float64         `json:"temperature,omitempty"`
	MaxTokens   int             `json:"max_tokens,omitempty"`
}

// AIChatResponse represents the OpenAI chat completion response
type AIChatResponse struct {
	ID      string `json:"id,omitempty"`
	Object  string `json:"object,omitempty"`
	Created int64  `json:"created,omitempty"`
	Model   string `json:"model,omitempty"`
	Choices []struct {
		Index        int           `json:"index"`
		Message      AIChatMessage `json:"message"`
		FinishReason string        `json:"finish_reason"`
	} `json:"choices"`
	Usage struct {
		PromptTokens     int `json:"prompt_tokens"`
		CompletionTokens int `json:"completion_tokens"`
		TotalTokens      int `json:"total_tokens"`
	} `json:"usage"`
	Error *struct {
		Message string `json:"message"`
		Type    string `json:"type"`
		Code    string `json:"code"`
	} `json:"error,omitempty"`
}

// AIPageGenerateRequest carries parameters for AI page synthesis
type AIPageGenerateRequest struct {
	Prompt   string `json:"prompt"`
	Template string `json:"template"` // "landing", "article", "default", "blank"
	Tone     string `json:"tone"`     // "professional", "modern", "creative", "promotional"
	Language string `json:"language"` // "id", "en"
	Model    string `json:"model,omitempty"` // optional model override
}

// AIPageGenerateResult holds structured page output generated by LLM
type AIPageGenerateResult struct {
	Title           string `json:"title"`
	Slug            string `json:"slug"`
	RouteURL        string `json:"route_url"`
	Template        string `json:"template"`
	Excerpt         string `json:"excerpt"`
	MetaTitle       string `json:"meta_title"`
	MetaDescription string `json:"meta_description"`
	MetaKeywords    string `json:"meta_keywords"`
	OGTitle         string `json:"og_title"`
	OGDescription   string `json:"og_description"`
	Content         string `json:"content"`
}

// GetAIConfig returns effective AI connection settings with fallback hierarchy:
// 1. Settings Studio (data/settings.json)
// 2. Environment variables (.env / os.Getenv)
// 3. Fallback defaults
func (e *Engine) GetAIConfig() (host, apiKey, defaultModel string) {
	settings := e.GetSettings()
	host = strings.TrimSpace(settings.OpenAIHost)
	apiKey = strings.TrimSpace(settings.OpenAIAPIKey)
	defaultModel = strings.TrimSpace(settings.OpenAIDefaultModel)

	if host == "" || apiKey == "" || defaultModel == "" {
		_ = godotenv.Load(".env")
		_ = godotenv.Load("../.env")
		_ = godotenv.Load("../../.env")
		if host == "" {
			host = strings.TrimSpace(os.Getenv("OPENAI_HOST"))
		}
		if apiKey == "" {
			apiKey = strings.TrimSpace(os.Getenv("OPENAI_APIKEY"))
		}
		if defaultModel == "" {
			defaultModel = strings.TrimSpace(os.Getenv("OPENAI_DEFAULT_MODEL"))
		}
	}

	if host == "" {
		host = "https://ai.sumopod.com"
	}
	if defaultModel == "" {
		defaultModel = "deepseek-v4-flash-0731:netra"
	}

	return host, apiKey, defaultModel
}

// BuildAIEndpoint normalizes the URL to .../v1/chat/completions
func (e *Engine) BuildAIEndpoint(host string) string {
	endpoint := strings.TrimRight(strings.TrimSpace(host), "/")
	if !strings.HasSuffix(endpoint, "/v1") && !strings.HasSuffix(endpoint, "/v1/chat/completions") && !strings.Contains(endpoint, "/chat/completions") {
		endpoint = endpoint + "/v1"
	}
	if !strings.HasSuffix(endpoint, "/chat/completions") {
		endpoint = endpoint + "/chat/completions"
	}
	return endpoint
}

// BuildAIModelsEndpoint normalizes the URL to .../v1/models
func (e *Engine) BuildAIModelsEndpoint(host string) string {
	endpoint := strings.TrimRight(strings.TrimSpace(host), "/")
	if strings.HasSuffix(endpoint, "/chat/completions") {
		endpoint = strings.TrimSuffix(endpoint, "/chat/completions")
	}
	if strings.HasSuffix(endpoint, "/chat") {
		endpoint = strings.TrimSuffix(endpoint, "/chat")
	}
	if !strings.HasSuffix(endpoint, "/v1") && !strings.HasSuffix(endpoint, "/v1/models") && !strings.Contains(endpoint, "/models") {
		endpoint = endpoint + "/v1"
	}
	if !strings.HasSuffix(endpoint, "/models") {
		endpoint = endpoint + "/models"
	}
	return endpoint
}

// AIModelInfo represents an item from GET /v1/models
type AIModelInfo struct {
	ID      string `json:"id"`
	Created int64  `json:"created,omitempty"`
	OwnedBy string `json:"owned_by,omitempty"`
}

type AIModelsResponse struct {
	Object string        `json:"object,omitempty"`
	Data   []AIModelInfo `json:"data,omitempty"`
	Models []AIModelInfo `json:"models,omitempty"`
}

// FetchAIModels queries the /v1/models endpoint from host using apiKey
func (e *Engine) FetchAIModels(ctx context.Context, host, apiKey string) ([]string, error) {
	if apiKey == "" {
		_, cfgKey, _ := e.GetAIConfig()
		apiKey = cfgKey
	}
	if host == "" {
		cfgHost, _, _ := e.GetAIConfig()
		host = cfgHost
	}
	if apiKey == "" {
		return nil, fmt.Errorf("API key is required to fetch models")
	}
	if host == "" {
		host = "https://ai.sumopod.com"
	}

	endpoint := e.BuildAIModelsEndpoint(host)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create models request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch models from %s: %w", endpoint, err)
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read models response: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("failed to fetch models (HTTP %d): %s", resp.StatusCode, string(bodyBytes))
	}

	var res AIModelsResponse
	if err := json.Unmarshal(bodyBytes, &res); err != nil {
		return nil, fmt.Errorf("invalid models JSON response: %w", err)
	}

	items := res.Data
	if len(items) == 0 && len(res.Models) > 0 {
		items = res.Models
	}

	var modelIDs []string
	seen := make(map[string]bool)
	for _, m := range items {
		id := strings.TrimSpace(m.ID)
		if id != "" && !seen[id] {
			seen[id] = true
			modelIDs = append(modelIDs, id)
		}
	}

	sort.Strings(modelIDs)
	return modelIDs, nil
}

// CallAIChatCompletion executes an HTTP request to the OpenAI-compatible chat API
func (e *Engine) CallAIChatCompletion(ctx context.Context, messages []AIChatMessage, maxTokens int, temperature float64) (string, error) {
	host, apiKey, model := e.GetAIConfig()
	return e.CallAIChatCompletionCustom(ctx, host, apiKey, model, messages, maxTokens, temperature)
}

// CallAIChatCompletionCustom executes an HTTP request with explicit credentials
func (e *Engine) CallAIChatCompletionCustom(ctx context.Context, host, apiKey, model string, messages []AIChatMessage, maxTokens int, temperature float64) (string, error) {
	if apiKey == "" {
		return "", fmt.Errorf("OpenAI API key is missing. Please configure OPENAI_APIKEY in .env or Settings Studio")
	}
	if host == "" {
		host = "https://ai.sumopod.com"
	}
	if model == "" {
		model = "deepseek-v4-flash-0731:netra"
	}

	endpoint := e.BuildAIEndpoint(host)

	reqPayload := AIChatRequest{
		Model:       model,
		Messages:    messages,
		Temperature: temperature,
		MaxTokens:   maxTokens,
	}

	reqBody, err := json.Marshal(reqPayload)
	if err != nil {
		return "", fmt.Errorf("failed to encode AI request: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(reqBody))
	if err != nil {
		return "", fmt.Errorf("failed to create HTTP request: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)

	client := &http.Client{
		Timeout: 90 * time.Second,
	}

	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("AI service request failed: %w", err)
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read AI service response: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("AI service HTTP %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var chatResp AIChatResponse
	if err := json.Unmarshal(bodyBytes, &chatResp); err != nil {
		return "", fmt.Errorf("failed to parse AI response JSON: %w (raw: %s)", err, string(bodyBytes))
	}

	if chatResp.Error != nil && chatResp.Error.Message != "" {
		return "", fmt.Errorf("AI error: %s", chatResp.Error.Message)
	}

	if len(chatResp.Choices) == 0 {
		return "", fmt.Errorf("AI returned no completion choices")
	}

	return chatResp.Choices[0].Message.Content, nil
}

// TestAIConnection performs a lightweight ping using active configurations
func (e *Engine) TestAIConnection() (latencyMs int64, modelName string, err error) {
	host, apiKey, model := e.GetAIConfig()
	return e.TestAIConnectionWith(host, apiKey, model)
}

// TestAIConnectionWith tests connectivity with specific host, apiKey, and model
func (e *Engine) TestAIConnectionWith(host, apiKey, model string) (latencyMs int64, modelName string, err error) {
	if host == "" {
		host = "https://ai.sumopod.com"
	}
	if model == "" {
		model = "deepseek-v4-flash-0731:netra"
	}
	start := time.Now()

	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()

	messages := []AIChatMessage{
		{Role: "user", Content: "Respond with the word 'OK' only."},
	}

	_, err = e.CallAIChatCompletionCustom(ctx, host, apiKey, model, messages, 10, 0.1)
	latency := time.Since(start).Milliseconds()

	if err != nil {
		return latency, fmt.Sprintf("%s (%s)", model, host), err
	}

	return latency, fmt.Sprintf("%s via %s", model, host), nil
}

// GeneratePageWithAI uses the configured LLM to synthesize a full custom page
func (e *Engine) GeneratePageWithAI(params AIPageGenerateRequest) (*AIPageGenerateResult, error) {
	prompt := strings.TrimSpace(params.Prompt)
	if prompt == "" {
		return nil, fmt.Errorf("prompt is required")
	}

	tpl := strings.ToLower(strings.TrimSpace(params.Template))
	if tpl == "" {
		tpl = "landing"
	}
	lang := strings.ToLower(strings.TrimSpace(params.Language))
	if lang == "" {
		lang = "id"
	}
	tone := strings.ToLower(strings.TrimSpace(params.Tone))
	if tone == "" {
		tone = "professional"
	}

	langInstruction := "Respond strictly in Bahasa Indonesia with elegant, natural, persuasive vocabulary."
	if lang == "en" {
		langInstruction = "Respond strictly in modern Silicon Valley English with crisp, authoritative copywriting."
	}

	templateGuide := ""
	switch tpl {
	case "landing":
		templateGuide = `Structure the HTML content for a modern high-conversion Landing Page:
- Hero Section: Catchy badge, bold <h1>, persuasive subtitle, primary CTA button, secondary CTA button, and guarantee note.
- Key Value Highlights / Stats: 3 or 4 metric counters (e.g. 99.9% Uptime, 10x Speed, 500+ Clients).
- Bento Grid / Features: 3 to 4 distinct feature cards with icons (SVG or emoji), heading, and descriptive paragraph.
- Showcase or Social Proof: Testimonial quote card or client trust badges.
- Call-to-Action Closing Card: High-impact banner with action button.
- Use inline semantic CSS styles with CSS variables compatible with modern design (colors: #0284c7, #2563eb, #0f172a, #f8fafc, #10b981; border-radius: 12px; padding: 2rem). Avoid raw black text or unstyled tables.`
	case "article":
		templateGuide = `Structure the HTML content for an authoritative, comprehensive Article / Whitepaper:
- Lead paragraph with larger font size (1.15rem) summarizing the core thesis.
- 3 to 5 structured sections with <h2> and <h3> headers.
- Key Takeaways or Quote Callout Box with a stylish border-left and light background.
- Bullet points or structured comparison where relevant.
- Clear conclusion section with actionable next steps.`
	default:
		templateGuide = `Structure the HTML content with clean modern formatting:
- Engaging headline and introduction.
- Modular content sections with clear typography and spacing.
- Actionable callout box or summary.`
	}

	systemPrompt := fmt.Sprintf(`You are an elite web architect, creative copywriter, and SEO specialist.
Generate a complete, production-ready website page based on the user's specification.

LANGUAGE RULE:
%s

TEMPLATE SPECIFICATION (%s):
%s

TONE OF VOICE:
%s

CRITICAL OUTPUT FORMAT:
You MUST respond with a single valid JSON object containing EXACTLY these keys. No conversational text, no markdown wrapping, just the raw JSON object:
{
  "title": "Clear, compelling page title",
  "slug": "url-friendly-slug-without-slash",
  "route_url": "/url-friendly-slug",
  "template": "%s",
  "excerpt": "Short 1-2 sentence executive summary",
  "meta_title": "SEO-optimized Title (50-60 chars)",
  "meta_description": "SEO Meta Description (120-155 chars with call to action)",
  "meta_keywords": "comma, separated, relevant, seo, keywords",
  "og_title": "OpenGraph Share Title",
  "og_description": "OpenGraph Share Summary",
  "content": "Full semantic HTML body string (use \\n for line breaks, avoid raw unescaped newlines in JSON values. Use single quotes ' for HTML tag attributes)"
}`, langInstruction, tpl, templateGuide, tone, tpl)

	ctx, cancel := context.WithTimeout(context.Background(), 150*time.Second)
	defer cancel()

	messages := []AIChatMessage{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: fmt.Sprintf("Create a page about: %s\nTemplate: %s\nTone: %s\nLanguage: %s", prompt, tpl, tone, lang)},
	}

	host, apiKey, defaultModel := e.GetAIConfig()
	modelToUse := defaultModel
	if strings.TrimSpace(params.Model) != "" {
		modelToUse = strings.TrimSpace(params.Model)
	}

	rawOutput, err := e.CallAIChatCompletionCustom(ctx, host, apiKey, modelToUse, messages, 6000, 0.7)
	if err != nil {
		return nil, fmt.Errorf("AI generation failed with model %s: %w", modelToUse, err)
	}

	result, err := parseAIJSONResponse(rawOutput)
	if err != nil {
		return nil, err
	}

	return postProcessAIResult(result, tpl), nil
}

// parseAIJSONResponse robustly parses the model's raw string into AIPageGenerateResult,
// automatically repairing unescaped newlines inside strings, missing closing quotes/braces,
// and falling back to regex extraction so generation never fails.
func parseAIJSONResponse(rawOutput string) (*AIPageGenerateResult, error) {
	cleaned := strings.TrimSpace(rawOutput)

	// 1. Strip markdown code fences (```json ... ``` or ``` ...)
	if strings.HasPrefix(cleaned, "```") {
		if idx := strings.Index(cleaned, "\n"); idx != -1 {
			cleaned = cleaned[idx+1:]
		}
		if idx := strings.LastIndex(cleaned, "```"); idx != -1 {
			cleaned = cleaned[:idx]
		}
		cleaned = strings.TrimSpace(cleaned)
	}

	// 2. Try direct unmarshal
	var res AIPageGenerateResult
	if err := json.Unmarshal([]byte(cleaned), &res); err == nil && res.Title != "" {
		return &res, nil
	}

	// 3. Extract JSON object bounds if wrapped in other conversational text
	startIdx := strings.Index(cleaned, "{")
	if startIdx != -1 {
		cleaned = cleaned[startIdx:]
	}

	// 4. Sanitize literal control characters (raw newlines, tabs) inside string literals
	sanitized := sanitizeJSONControlChars(cleaned)
	if err := json.Unmarshal([]byte(sanitized), &res); err == nil && res.Title != "" {
		return &res, nil
	}

	// 5. Auto-repair truncated JSON (close dangling strings & brackets)
	repaired := repairTruncatedJSON(sanitized)
	if err := json.Unmarshal([]byte(repaired), &res); err == nil && res.Title != "" {
		return &res, nil
	}

	// Also try repairing before sanitizing in case sanitization altered lengths
	repairedOrig := repairTruncatedJSON(cleaned)
	sanitizedRepaired := sanitizeJSONControlChars(repairedOrig)
	if err := json.Unmarshal([]byte(sanitizedRepaired), &res); err == nil && res.Title != "" {
		return &res, nil
	}

	// 6. Regex / Structured extraction fallback (guaranteed extraction of partial/truncated output)
	fallbackRes := extractFieldsWithRegex(cleaned)
	if fallbackRes.Title != "" || fallbackRes.Content != "" {
		return fallbackRes, nil
	}

	return nil, fmt.Errorf("failed to parse AI JSON response: %s", cleaned)
}

func sanitizeJSONControlChars(s string) string {
	var buf strings.Builder
	buf.Grow(len(s) + 128)

	inQuotes := false
	var escaped bool

	for i := 0; i < len(s); i++ {
		b := s[i]
		if b == '\\' && !escaped {
			escaped = true
			buf.WriteByte(b)
			continue
		}

		if b == '"' && !escaped {
			inQuotes = !inQuotes
			buf.WriteByte(b)
			escaped = false
			continue
		}

		if inQuotes {
			switch b {
			case '\n':
				buf.WriteString(`\n`)
			case '\r':
				buf.WriteString(`\r`)
			case '\t':
				buf.WriteString(`\t`)
			default:
				buf.WriteByte(b)
			}
		} else {
			buf.WriteByte(b)
		}

		escaped = false
	}

	return buf.String()
}

func repairTruncatedJSON(s string) string {
	s = strings.TrimSpace(s)
	if !strings.HasPrefix(s, "{") {
		return s
	}

	inQuotes := false
	var escaped bool
	for i := 0; i < len(s); i++ {
		b := s[i]
		if b == '\\' && !escaped {
			escaped = true
			continue
		}
		if b == '"' && !escaped {
			inQuotes = !inQuotes
		}
		escaped = false
	}

	if inQuotes {
		s += `"`
	}

	lastBrace := strings.LastIndex(s, "}")
	if lastBrace == -1 || lastBrace < strings.LastIndex(s, `"`) {
		s += "\n}"
	}

	return s
}

func extractFieldsWithRegex(raw string) *AIPageGenerateResult {
	res := &AIPageGenerateResult{}

	extract := func(key string) string {
		re := regexp.MustCompile(fmt.Sprintf(`"%s"\s*:\s*"([^"\\]*(?:\\.[^"\\]*)*)"`, key))
		m := re.FindStringSubmatch(raw)
		if len(m) > 1 {
			val := m[1]
			val = strings.ReplaceAll(val, `\"`, `"`)
			val = strings.ReplaceAll(val, `\n`, "\n")
			val = strings.ReplaceAll(val, `\t`, "\t")
			val = strings.ReplaceAll(val, `\\`, `\`)
			return strings.TrimSpace(val)
		}
		return ""
	}

	res.Title = extract("title")
	res.Slug = extract("slug")
	res.RouteURL = extract("route_url")
	res.Template = extract("template")
	res.Excerpt = extract("excerpt")
	res.MetaTitle = extract("meta_title")
	res.MetaDescription = extract("meta_description")
	res.MetaKeywords = extract("meta_keywords")
	res.OGTitle = extract("og_title")
	res.OGDescription = extract("og_description")

	// For content: extract everything after "content":\s*"
	contentRe := regexp.MustCompile(`"content"\s*:\s*"([\s\S]*)`)
	contentMatches := contentRe.FindStringSubmatch(raw)
	if len(contentMatches) > 1 {
		rawContent := contentMatches[1]
		rawContent = strings.TrimSpace(rawContent)
		if strings.HasSuffix(rawContent, `}`) {
			rawContent = strings.TrimSuffix(rawContent, `}`)
			rawContent = strings.TrimSpace(rawContent)
		}
		if strings.HasSuffix(rawContent, `"`) {
			rawContent = strings.TrimSuffix(rawContent, `"`)
		}
		rawContent = strings.ReplaceAll(rawContent, `\"`, `"`)
		rawContent = strings.ReplaceAll(rawContent, `\n`, "\n")
		rawContent = strings.ReplaceAll(rawContent, `\t`, "\t")
		rawContent = strings.ReplaceAll(rawContent, `\\`, `\`)
		res.Content = strings.TrimSpace(rawContent)
	}

	return res
}


func postProcessAIResult(res *AIPageGenerateResult, requestedTpl string) *AIPageGenerateResult {
	if res.Template == "" {
		res.Template = requestedTpl
	}
	if res.Slug == "" && res.Title != "" {
		res.Slug = strings.ToLower(strings.ReplaceAll(res.Title, " ", "-"))
	}
	res.Slug = strings.TrimPrefix(strings.TrimSpace(res.Slug), "/")
	if res.RouteURL == "" {
		res.RouteURL = "/" + res.Slug
	} else if !strings.HasPrefix(res.RouteURL, "/") {
		res.RouteURL = "/" + res.RouteURL
	}
	if res.MetaTitle == "" {
		res.MetaTitle = res.Title
	}
	if res.MetaDescription == "" {
		res.MetaDescription = res.Excerpt
	}
	if res.OGTitle == "" {
		res.OGTitle = res.MetaTitle
	}
	if res.OGDescription == "" {
		res.OGDescription = res.MetaDescription
	}
	return res
}
